---
- name: create controller credentials for each student
  hosts: localhost
  gather_facts: no
  vars:
    controller_validate_certs: false
    number_of_workshop_students: 2
    workshop_id: rh0fe3
    workshop_password: "GpplzFRwp5BpUV"
    controller_components:
      - credentials
      - job_templates
#      - projects
    controller_credentials:
      - name: "student{{student_number}}_controller_cred"
        credential_type: "Red Hat Ansible Automation Platform"
        organization: Default
        inputs: 
          host: student{{student_number}}.{{workshop_id}}.example.opentlc.com
          username: admin
          password: "{{workshop_password}}"
        ignore_errors: true
    #controller_projects:
      # - name: Fact Scan{{student_number}}
      #   organization: Default
      #   scm_type: git
      #   scm_url: 'https://github.com/ansible/awx-facts-playbooks.git'
    controller_templates:
      - name: "WORKSHOP / Setup Student{{student_number}}"
        job_type: run
        inventory: "Workshop Inventory"
        project: "Workshop Student Setup"
        playbook: "4_1_build_student_ac_objects.yml"
        execution_environment: Default execution environment
        become_enabled: true
        credentials:
        - "student{{student_number}}_controller_cred"

  tasks:
    - name: create all student controller creds
      include_tasks: 1_2_build_student_controller_creds.yml
      loop: "{{ query('sequence', 'start=1 end='+(number_of_workshop_students)|string) }}"
      loop_control:
        loop_var: student_number
        label: "{{ student_number }}"

    # - name: create all student controller creds
    #   include_tasks: 1_3_build_student_job_templates.yml
    #   loop: "{{ query('sequence', 'start=1 end='+(number_of_workshop_students)|string) }}"
    #   loop_control:
    #     loop_var: student_number
    #     label: "{{ student_number }}"

    # - name: set up controller creds
    #   include_role:
    #     name: "setup_workshop_student_controller_creds"
      # loop: "{{ controller_components }}"
      # when:
      #   - controller_components | d("") | length > 0
