---
- hosts: localhost
  gather_facts: no
  vars_files:
    - workshop/setup.yml
    - workshop/secrets.yml
  vars:
    controller_validate_certs: false
    number_of_workshop_students: 2
    workshop_ID: rhceed

  tasks:
    - name: set up controller objects for single host
      include_tasks: setup_workshop_child.yml    
      delegate_to: "student{{ item }}.{{workshop_ID}}.example.opentlc.com"
      loop: "{{ number_of_workshop_students }}"
  
    

    # - name: Log Demo
    #   ansible.builtin.uri:
    #     url: https://docs.google.com/forms/d/e/1FAIpQLSdIZ77YpETjEfGOoYlXtMnQiU-6M7QFlb2hJA4ujo25QYb2jw/formResponse
    #     method: POST
    #     body: "ifq&entry.1569353616={{ demo }} &entry.498055740={{ lookup('ansible.builtin.env', 'AWX_HOST') }}&sumbit=Submit"
    #   ignore_errors: true

    # - name: Print Message
    #   debug:
    #     msg: "{{ user_message }}"
    #   when: user_message is defined
