---
- name: create controller credentials for each student
  hosts: localhost
  gather_facts: no
  # vars_files:
  #   - "{{demo}}/setup_controller_creds.yml"
  #   - "{{demo}}/secrets.yml"
  vars:
    controller_validate_certs: false
    number_of_workshop_students: 2
    workshop_id: rh0fe3
    workshop_password: ""

  tasks:   
    - name: set up controller creds
      include_role:
        name: "setup_workshop_student_controller_creds"
      # loop: "{{ controller_components }}"
      # when:
      #   - controller_components | d("") | length > 0
